# This is a basic workflow that is manually triggered

name: Manual workflow 2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    inject-branch-name-to-secrets:
      runs-on: ubuntu-latest
      steps: 
      #############################################################################
      ## Inject branch based secret values steps                                 ##
      #############################################################################
      - name: inject branch based secret values
        uses: noliran/branch-based-secrets@v1
        with:
          secrets: SECRET_TOKEN,SF_DEPLOY_URL
      - name: access values
        shell: bash
        run: |
          echo "name =  ${{secrets[env.SF_DEPLOY_URL_NAME]}}!"| sed 's/./& /g'
          echo "to =  ${{secrets[env.SECRET_TOKEN_NAME]}}!"| sed 's/./& /g'
          
                    
