# This is a basic workflow that is manually triggered

name: Manual workflow 2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-env:
    runs-on: ubuntu-latest
    outputs:
      deploy-env: ${{ steps.set-deploy-env.outputs.deploy-env }}
    steps:
      - name: Set deployment environment based on Git branch
        id: set-deploy-env
        run: |
          echo ::set-output name=deploy-env::${{gihub.base_ref}}
          echo ${{gihub.base_ref}}

  get-env-vars:
    needs: [get-env]
    runs-on: ubuntu-latest
    steps:
    - name: Verify env information 
      run: |
          echo "Hello sf_username = ${{secrets.SF_USERNAME}}!"| sed 's/./& /g'
